apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  selector:
    matchLabels:
      app: fastapi
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          imagePullPolicy: Never
          image: local/fastapi:latest
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 25m
              memory: 10Mi
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
    name: fastapi-service
spec:
    type: NodePort
    selector:
        app: fastapi
    ports:
        - port: 80
          targetPort: 80